# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: circle_detection.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ircle_detection.proto\"I\n\x0b\x42oundingBox\x12\r\n\x05x_min\x18\x01 \x01(\x05\x12\r\n\x05y_min\x18\x02 \x01(\x05\x12\r\n\x05x_max\x18\x03 \x01(\x05\x12\r\n\x05y_max\x18\x04 \x01(\x05\":\n\tDetection\x12\x11\n\tobject_id\x18\x01 \x01(\x05\x12\x1a\n\x04\x62\x62ox\x18\x02 \x01(\x0b\x32\x0c.BoundingBox\"8\n\x04\x44\x61ta\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12\x1e\n\ndetections\x18\x02 \x03(\x0b\x32\n.Detection\"\x1e\n\x0bRequestData\x12\x0f\n\x07message\x18\x01 \x01(\t2@\n\x16\x43ircleDetectionService\x12&\n\rGetStreamData\x12\x0c.RequestData\x1a\x05.Data0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'circle_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOUNDINGBOX']._serialized_start=26
  _globals['_BOUNDINGBOX']._serialized_end=99
  _globals['_DETECTION']._serialized_start=101
  _globals['_DETECTION']._serialized_end=159
  _globals['_DATA']._serialized_start=161
  _globals['_DATA']._serialized_end=217
  _globals['_REQUESTDATA']._serialized_start=219
  _globals['_REQUESTDATA']._serialized_end=249
  _globals['_CIRCLEDETECTIONSERVICE']._serialized_start=251
  _globals['_CIRCLEDETECTIONSERVICE']._serialized_end=315
# @@protoc_insertion_point(module_scope)
